
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WZQ1993/config
          search-paths: /{application}
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://172.19.1.0:9000/eureka/
debug: false