version: '2'
services:
  zk_server:
    image: daocloud.io/library/zookeeper:3.3.6
    restart: always
  kafka_server:76y654628
    image: bolingcavalry/kafka:0.0.1
    links:
      - zk_server:zkhost
    command: /bin/sh -c '/usr/local/work/start_server.sh'
    restart: always
  message_producer:
    image: bolingcavalry/kafka:0.0.1
    links:
      - zk_server:zkhost
      - kafka_server:kafkahost
    restart: always
  message_consumer:
    image: bolingcavalry/kafka:0.0.1
    links:
      - zk_server:zkhost
    restart: always