---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangzq1.
--- DateTime: 2020-5-7 15:42
---
if redis.call('get', KEYS[1]) == KEYS[2] then
    return redis.call('del', KEYS[1])
else
    return 0
end