---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangzq1.
--- DateTime: 2020-5-7 15:42
---
local lockKey = KEYS[1]
local lockValue = KEYS[2]

local setNxResp = redis.call('SETNX', lockKey, lockValue)
if setNxResp == true then
    local setExResp = redis.call('SETEX', lockKey, 3600, lockValue)
    return setNxResp
else
    return setNxResp
end